# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb2475f2f6a45f002a07c57a96ea81e7d53b7164a4cfede64d4254ff5d89a6cf917c37c7c9b636960629d01ec779565598e026b54ff78df4cf7fa85213cb6bbf

test:
  secret_key_base: 5f625465151a30ce89a75fefada65ae7705e4d88a906c4a2d47d951a73e815fc6a7c5325d276f48156dccca6f275b79267a460ebcc72b46a94727dad262a0960

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
